version: "3.9"
   
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  cache:
    image: memcached
    ports:
      - "11211:11211"
  github_pop_svc:
    build: .
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py showmigrations &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/github_pop_svc
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
      - cache
